#:schema node_modules/wrangler/config-schema.json
name = "lyricsplus"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-12"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "LYRICSPLUS"
id = "19a4fc41ceb3469fb12a99b99867c772"
preview_id = "19a4fc41ceb3469fb12a99b99867c772"

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

